### ISSUE TITLE
Allow staff to open tickets

### ISSUE THREAD

**Issue by ChampionJ** [CHamburr/modmail#1]
**Please describe the feature you'd like**
A command to allow staff with an accessrole to open a ticket with specific member of the server with a command like `=open <member>`

**Describe the motivation for the feature**
Sometimes staff need to be proactive and start conversations with members involved in issues. Currently the only way to facilitate this is to ask the user to DM the ModMail bot to start a ticket, so adding a method for staff to open a new ticket with a specific user would streamline the process and make it much more professional feeling.

**Comment by CHamburr** [comment]
@ChampionJ Would you be able to add that feature?

**Comment by ChampionJ** [comment]
@CHamburr I could potentially look into it if I find some time in the future, though I haven't really used Python much so it'd be spotty.

**Comment by Anonymyous678** [comment]
This feature will be cool. Pls add it

**Comment by CHamburr** [comment]
Closing because haven't heard anything for a while, also this feature is really abusable.
