### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by SnowyJaguar1034** [chamburr/modmail#102]
**Please describe the feature you'd like**
Docker Support for the bot

**Describe the motivation for the feature**
Making it a more visible 'plan' than being in just the suggestions channel

**Comment by Trenly** [comment]
I had suggested this a while ago in #8
Glad to see that it has come up again, as it would make self-hosting a lot easier

**Comment by SnowyJaguar1034** [comment]
> I had suggested this a while ago in #8 Glad to see that it has come up again, as it would make self-hosting a lot easier

Yeah I'd also suggested it at some point (in the 300's I think). A few weeks ao I decided to go through suggestions and add all of the approved or likley to be approved suggestions onto GitHub as issues to make it more clear what ppl wnt worked on

**Comment by chamburr** [comment]
Docker support is here! be1864096f36c1985acc806688c7641fb861d01a
