### ISSUE TITLE
Remove paginator for server list when unnecessary

### ISSUE THREAD

**Issue by SnowyJaguar1034** [chamburr/modmail#103]
**Please describe the feature you'd like**
A note attached to the footer of the server selection menu saying that the user's options will not change when there are 10 or fewer servers (one page) shown.

**Describe the motivation for the feature**
[Per approved suggestion 321.](https://canary.discord.com/channels/576016832956334080/576765354051633178/825943471823126548) - Users report that the page reactions are confusing when opening a ModMail, especially if they only belong to one server or few enough servers that multiple pages do not appear.

**Describe alternatives you've considered**
Numbering the pages and included a total page number or just not adding the ◀▶ reactions and the `Use the reactions to flip pages` message for lists that contain 10 or fewer servers

**Comment by chamburr** [comment]
I think we should implement both of the alternatives instead.
