### ISSUE TITLE
Ticket transfer command

### ISSUE THREAD

**Issue by SnowyJaguar1034** [chamburr/modmail#107]
**Please describe the feature you'd like**
A way to transfer tickets between different staff departments (moderators, sales, support, admins etc). `=transfer <role>` could be the command.

**Describe the motivation for the feature**
[Per approved suggestion 175](https://canary.discord.com/channels/576016832956334080/576765354051633178/753247391632588810) (it's marked as implemented but i think that's a mistake) - _Add a transfer command. This would be useful if the ModMail is used by different staff departments in the server, plus there's no other ModMail public bots with that feature. How would it work? When a ticket is open, the default support roles will be able to see it, then they could do =transfer <role> and that would display a message saying the user is being transferred to that role and would allow people that has the target role to see and type in the channel and would also ping that role. I'm sorry if my explanation is a bit confusing but i hope you understand.
_

**Addidional Context**
This suggestion was also raised in [this message](https://canary.discord.com/channels/576016832956334080/576765354051633178/599420413574905866) before carl's suggestions were added, back when V2 was still in development.

**Comment by chamburr** [comment]
I think the solution was to move the channel manually to different categories (hence different permissions). It was marked as implemented because before that, users were not able to move the channel to a different category. As for ticket transfer command, I don't think I'm interested in that.
