### ISSUE TITLE
Explain how this isn't a scam

### ISSUE THREAD

**Issue by SoniEx2** [chamburr/modmail#142]
**Describe the bug**
Currently there's nothing that explains how this isn't a scam. It's definitely a massive privacy risk tho.

**To Reproduce**
1. Try to use the bot for the first time.
2. Notice it asks for permissions from not-the-server-admin.

**Expected behavior**

The bot should not need access to users' accounts for its functionality. There is no explanation anywhere about why it does so.

**Screenshots**

N/A

**Additional context**

Neither the privacy policy nor the terms of service, as posted on the website, address the bot's features and functionality at all.

**Comment by chamburr** [comment]
?
