### ISSUE TITLE
replying to a ModMail DM leads to timeout waiting for user reaction

### ISSUE THREAD

**Issue by buck2202** [chamburr/modmail#143]
I posted this in the support discord as well, but found the github tracker afterwards and wanted to include here for easier tracking

**Describe the bug**
If a user *replies* to a DM from the bot rather than just sending a message in the DM conversation, the confirmation/server-select dialog appears as intended, but the bot does not seem to notice reactions to it and times out

**To Reproduce**
(see screenshots)

**Expected behavior**
The bot should either forward the message as expected, or notice that the message is a reply, and explain this limitation to the user and ask that their messages _not_ be replies to individual bot messages.

**Screenshots**
![Screenshot from 2022-11-30 12-43-48](https://user-images.githubusercontent.com/2069200/204870970-2384f721-f8fb-4702-8f31-1c785e042efd.png)
![Screenshot from 2022-11-30 12-46-49](https://user-images.githubusercontent.com/2069200/204871009-d99185ea-4b1c-45e9-ba63-9f7a77c33b26.png)

**Additional context**
Unsure if this is an unintended bug or known limitation, but it would be great to have additional guidance for inexperienced users if this isn't an easily-fixable problem

**Comment by buck2202** [comment]
hi, just wondering if this fix has gone live? I'm still able to reproduce the issue as in the initial report, but figure it's possible that I'm just trying before the new code has been deployed

**Comment by chamburr** [comment]
No, it’s not deployed yet. I’m still in the midst of setting up a new deploy system.
