### ISSUE TITLE
Channel command alternative to msg ModMail

### ISSUE THREAD

**Issue by Revenger** [chamburr/modmail#144]
It would be good to have a channel command so users can create the support ticket rather than direct messaging the bot.
For example
`/staffmsg I'm being bullied can we chat`

This would do the same thing as messaging the bot directly.

Reason for this comes from privacy concerns users of my server have with the ModMail bot wanting access to their channel lists or not wanting to DM the bot directly.

Here's a comment from a user.
`Says it needs to be able to see my entire servers list, which I am not really comfortable it knowing tons about me`
You can get past that by
`=send ServerID message`

Another mentioned he didn't want to message the bot directly.

So with a openticket command it would open the channel automatically without having to go through the bot user.

Looked at mee6 custom commands as well as read through the command list a few times.

**Comment by Revenger** [comment]
Saw the ticket was closed without response.

So is it planned for members to be able to create tickets from a channel in the server rather than bot DM?

As the msg command won't work and is bot DM only.

**Comment by chamburr** [comment]
No, it's not planned. Just DM the bot.

**Comment by Revenger** [comment]
That's a shame as a lot of users don't want to do that unfortunately and worries rather keep things they do all in the server.

**Comment by chamburr** [comment]
Use another bot.
