### ISSUE TITLE
Webhooks for Message Log

### ISSUE THREAD

**Issue by dlsnyder8** [chamburr/modmail#155]
**Please describe the feature you'd like**
Suggestion #523 - add webhook support for message log

TODO after d.py2.1 migration

**Comment by chamburr** [comment]
I don't understand the purpose of this?

**Comment by dlsnyder8** [comment]
It will reduce issues with permissions and has more formatting options than a Bot/Client does, so it will open more customization options in the future.

Holding until d.py upgrade because there are better built in functions for webhooks than in 1.7.2

**Comment by chamburr** [comment]
Sorry, I don't think that's convincing. There's no point in mitigating user errors with this feature, when setting the permissions correctly is necessary in general. I suspect this even adds an additional permission requirement of managing webhooks.
