### ISSUE TITLE
Add 'Create' command for use in server

### ISSUE THREAD

**Issue by dlsnyder8** [chamburr/modmail#157]
**Please describe the feature you'd like**
Suggestion 500 (and many more)
Add a command that can be used in a server to create a ticket for that server

Implement with Slash commands so that messages can be ephemeral and secret to avoid sharing details w/ other server members

TODO d.py2.1+ upgrade

**Comment by chamburr** [comment]
Going to merge this with #131 because they are quite similar

**Comment by dlsnyder8** [comment]
Oh that's true - forgot that was a ticket
