### ISSUE TITLE
Non-member can't be whitelisted

### ISSUE THREAD

**Issue by SnowyJaguar1034** [chamburr/modmail#160]
**Describe the bug**
If a user is not in the server when staff use the whitelist command then the command fails because it cannot retrieve the member.

**To Reproduce**
1. Grab a non-member's ID from the blacklist
2. use the `whitelist` command to whitelist the ID
3. See error

**Expected behavior**
The bot should accept a `discord.user` argument instead of a member argument
OR
the error message should be updated to state that the member was not found in the server but that the user has been removed from the blacklist.

**Screenshots**
![image](https://github.com/chamburr/modmail/assets/51423344/7acf98ff-87cd-4974-a99e-eccad42f3a1a)

**Additional context**

**Comment by Scyye** [comment]
I feel like all arguments that accept "member" should be changed to user

is there any place this wouldnt be acceptable?

**Comment by SnowyJaguar1034** [comment]
> I feel like all arguments that accept "member" should be changed to user
> 
> is there any place this wouldnt be acceptable?

I think checking `user` has more API requests to discord than `member` does (I could be wrong), so it's better to use `member` where possible. Also there's not many commands that could really benefit from the `user` arg other than `whitelist` and `blacklist`, which I updated in the pr.

**Comment by Scyye** [comment]
The `fetch_user` method in discord.py and the `fetch_member` method for fetching a member in a guild comparison of API requests

1. **fetch_user**
   - **Purpose:** Fetches a user globally, not limited to a specific guild.
   - **API Requests:** Generally uses fewer API requests as it's a global search for a user.
[1](https://discordpy.readthedocs.io/en/stable/api.html) 
[2](https://github.com/Rapptz/discord.py/issues/2578) 
[3](https://stackoverflow.com/questions/54499864/discord-py-get-user-object-from-id-tag)

2. **guild.fetch_member**
   - **Purpose:** Fetches a member in a specific guild.
   - **API Requests:** May use more API requests, especially in large guilds, as it's specific to a particular guild.
[4](https://stackoverflow.com/questions/67767330/trying-to-fetch-all-members-in-a-guilddiscord-py-rewrite)
[5](https://docs.nextcord.dev/en/stable/api.html)
[6](https://docs.pycord.dev/en/stable/api/models.html)

**Comment by chamburr** [comment]
If you search for the remaining cases where member is still used, you'll realise why they cannot be changed to user.

This issue is fixed in fec862a63b94bbcf632ff6d17d82cb74ab8118c3.
