### ISSUE TITLE
[request] "Are you sure?"/FAQ reply buffer for modmail

### ISSUE THREAD

**Issue by kevansevans** [chamburr/modmail#25]
**Please describe the feature you'd like**

A way to set an automatic reply message to send to a user before the issue is submitted for server staff to review. It should be something staff members can set. When user first contacts modmail, they will automatically be sent this FAQ to read over, and if it doesn't solve their issue, the user should reply again to submit their issue.

**Describe the motivation for the feature**

I help run a official game server, and we get a lot of modmail submissions on topics we can't help with because people assume the volunteer staff are official employees. it would help minimize the amount of clutter we deal with daily.

**Comment by chamburr** [comment]
Have you tried putting FAQs in a channel of the server? Personally I think that would be more effective and better than to implement it in the bot.

**Comment by kevansevans** [comment]
Unfortunately, most users suffer from a bad case of never reading the #readme where something like that would be useful. Most of them will even openly admit they immediately went towards who was online and by some miracle saw there was a modmail.

**Comment by chamburr** [comment]
Hey there, unfortunately I don't think this is something I'm interested in implementing at the moment. Another confirmation message on top of the current one doesn't sound very user-friendly to me. I suggest that you could put your #readme channel at the top of the channel list so it is more noticeable, or set ModMail's role name as something like "read #readme first". Hopefully this helps you :)
