### ISSUE TITLE
saying this error "improper token has been passed" on the self-hosted version

### ISSUE THREAD

**Issue by sweetchikoo2403** [CHamburr/modmail#4]
![Screenshot (87)](https://user-images.githubusercontent.com/52192223/76950145-9e64b180-692f-11ea-97b6-cc6078595517.png)

The terminal is saying this error "improper token has been passed" on the self-hosted version in which the bot has the same token in the config.py file

**Comment by CHamburr** [comment]
The error is self-explanatory, the token you passed is invalid. My best guess is that you did not save your config file.

Also, for your own safety, please regenerate the token since you posted it here.
