### ISSUE TITLE
Add anonymous ticketing as an option either by user or server

### ISSUE THREAD

**Issue by YeahNahCunt** [CHamburr/modmail#5]
**Please describe the feature you'd like**

Allow users to send messages anonymously or the server mods being able to turn it on as whole

**Describe the motivation for the feature**

Allows members to share more sensitive information with moderators if needed

**Describe alternatives you've considered**

Already forked code and begun trying to do it myself as a learning experience 

**Additional context**
nope

**Comment by CHamburr** [comment]
@YeahNahCunt Hello, thanks for helping out!

Enabling anonymous tickets for the server as a whole is cool. Please go ahead implementing it and make a pull request whenever you're ready.

However, allowing users to send anonymous messages is not a good idea. First, majority of the servers, as I would say, would not want users to be anonymous. Second, it would break more things than you would expect and a lot of code would have to be changed.

**Comment by YeahNahCunt** [comment]
Its no problem at all if  I can get it to work

So far I've been able to add the feature to turn it on and off for sending and receiving messages anonymously.

The main bit that I know will need major changes in code now is the naming of the rooms and not to reference the user ID in the room description but store those ticket details in the SQL

**Comment by CHamburr** [comment]
@YeahNahCunt Sorry, you might have gotten me wrong. Please do not implement anonymous user messages. Thanks!

**Comment by CHamburr** [comment]
Implemented myself. https://github.com/CHamburr/modmail/commit/0808910909e848535d5855649d73eb1feeba46be
