### ISSUE TITLE
How to Reply for tickets

### ISSUE THREAD

**Issue by sweetchikoo2403** [CHamburr/modmail#6]
![Screenshot (167)](https://user-images.githubusercontent.com/52192223/79719722-c8c5d800-82fc-11ea-99bc-1f89f2914b17.png)
I have to create new tickets instead of replying to them. How to reply to a single ticket.
Additional info:- Revoke my ModMail Discord Ban as I apologise to the team that not to make chain messages again

**Comment by CHamburr** [comment]
Unbanned, please report issue in the support server.
