### ISSUE TITLE
Feature Request for ModMail

### ISSUE THREAD

**Issue by Diabolical5777** [chamburr/modmail#78]
**Improve the userinfo command**
Right now the userinfo command seems kind of boring to be honest, it can be improved alot to make it way more attractive, and I do know that the command is not used alot but it would still be nice to have a nice looking userinfo command in my opinion

As of now, for the "Roles" section in the command, the roles are not mentioned, it looks boring if I'm being honest, and also there is a section of "Status" (which is idle, do not disturb or online) which I feel is unnecessary and can be replaced my "Nickname". 
I have coded my ideas for you to look through and it would be appreciated if you consider it thanks :)

For comparision, this is the difference (my one is by Test Bot")
![Screenshot (291)](https://user-images.githubusercontent.com/84365102/118596656-b72f5800-b7bc-11eb-8131-57e648ef627c.png)
![Screenshot (293)](https://user-images.githubusercontent.com/84365102/118596737-d29a6300-b7bc-11eb-8863-f92cf4425cf5.png)
![image](https://user-images.githubusercontent.com/84365102/118597778-37a28880-b7be-11eb-86f0-d90c52230b0c.png)
Edit:
It would have to be updated to
roles = member.roles[0:] 
So that it shows the "@everyone" role

**Comment by SnowyJaguar1034** [comment]
Hey, Could you edit this so that the `=userinfo` shows the users status msg as well, and maybe put in a default _User does not have a status msg_ filler for when users don't have a status msg

**Comment by Diabolical5777** [comment]
> Hey, Could you edit this so that the `=userinfo` shows the users status msg as well, and maybe put in a default _User does not have a status msg_ filler for when users don't have a status msg

You mean maybe like listening to spotify or something like that or do you mean the user putting a custom message as a status

**Comment by SnowyJaguar1034** [comment]
> > Hey, Could you edit this so that the `=userinfo` shows the users status msg as well, and maybe put in a default _User does not have a status msg_ filler for when users don't have a status msg
> 
> You mean maybe like listening to Spotify or something like that or do you mean the user putting a custom message as a status

Yeah, sort of both. You know how users can set a custom status msg, it would be cool if the bot could show the status msg in the `=userinfo` command. and I guess the status msg would change if they were listening to Spotify but i don't know what info the bot would receive about that

**Comment by Diabolical5777** [comment]
Updated command:

[whois.txt](https://github.com/chamburr/modmail/files/6524903/whois.txt)

**Comment by Diabolical5777** [comment]
Updated userinfo command:
[whois.txt](https://github.com/chamburr/modmail/files/6524913/whois.txt)

**Comment by chamburr** [comment]
Implemented in e0b0bce2776634c7ea2d36f2ea642a04d9c20009.
