### ISSUE TITLE
[Suggestion] Containerize the Application for Docker

### ISSUE THREAD

**Issue by Trenly** [CHamburr/modmail#8]
By putting the entire application into a docker container, it will become more versatile and accessible for those who wish to develop and test locally. Using a docker container, the application can also be run on windows using the Windows Subsystem for Linux. Additionally, the dockerfile would allow the docker build to automatically install and configure the required applications {Python, PostgreSQL, and Redis} as well as install all the required modules

**Comment by CHamburr** [comment]
I do not have any plans for ModMail to support docker. Personally running it standalone is good enough for me to test and run. If you'd like to, you can make a pull request with the necessary docker files.
