### ISSUE TITLE
Improve the "serverinfo" command with more details and information

### ISSUE THREAD

**Issue by Diabolical5777** [chamburr/modmail#80]
**A more detailed serverinfo command with more useful information**
I know that the miscellaneous commands are not used alot but I think it would just be cool having the extra details, would understand if this idea is thought as unnecessary. Anyways, instead of the current "emotes: (total emotes in the guild)"
I think it would be more useful with more info, the extra details would be, amount of animated, normal and total emotes in the guild. I think this would be cool. Also information about the server boost status, maybe? For the details about server emotes (animated, normal and total), you would first have to import this:
 **from collections import OrderedDict, deque, Counter**

Just a small and simple example of the above output and code, (to add on to the current code):
![image](https://user-images.githubusercontent.com/84365102/118673599-3008d100-b80a-11eb-8997-657a029c53be.png)
![image](https://user-images.githubusercontent.com/84365102/118673708-47e05500-b80a-11eb-83df-7d61b2081a7d.png)

**Comment by SnowyJaguar1034** [comment]
Hey, Could you edit this so that the `=userinfo` shows the users status msg as well, and maybe put in a default _User does not have a status msg_ filler for when users don't have a status msg

**Comment by Diabolical5777** [comment]
Updated serverinfo command:
[serverinfo.txt](https://github.com/chamburr/modmail/files/6524925/serverinfo.txt)

**Comment by chamburr** [comment]
I think those information are quite meaningless.
