### ISSUE TITLE
Ability to assign a ticket to a user

### ISSUE THREAD

**Issue by RodoggA** [chamburr/modmail#88]
**Please describe the feature you'd like**
If we could get the ability to assign a user to a ticket that would be awesome.
Currently, when a ticket is generated, it's viewable by a role (e.g Support Team), Having the ability to assign to a specific user or role from that point onward would help when dealing with a request such as 
- Staff Complaints
- Suggestions

**Describe the motivation for the feature**
Currently within our community tickets are generated and the whole support team is able to interact with these, we are looking to expand on this system and allow suggestion/complaints about a staff member who are being disrespectful etc. Having the ability to assign tickets to either the SM (Myself) or our dev team (@Dev Team) once it comes into the support team would help enhance our process flows.

**Describe alternatives you've considered**
Alternative to this, I've thought about getting a custom bot developed to meet our community needs.

**Comment by chamburr** [comment]
That's an internal staff issue which you could resolve through proper communication.
