### ISSUE TITLE
Increase end user experience with "category" command

### ISSUE THREAD

**Issue by dlsnyder8** [chamburr/modmail#91]
**Describe the bug**
If a user deletes the modmail category and logging channel, then if they run the `=category` command the bot will only create the new category. To increase the end user experience, the bot should check for if a logging channel already exists. If it does, the bot should move it into the new category. If it does not exist, the bot should create a new logging channel.

**To Reproduce**
Run `=setup`
Delete category + logging channel
Run `=category <name>`

**Expected behavior**
It would be expected that the `=category` command functions similarly to the `=setup` command if `=logging` is enabled and there is not a logging channel currently in the server.

**Comment by chamburr** [comment]
This is intended behaviour.
