### ISSUE TITLE
Add count to snippet list

### ISSUE THREAD

**Issue by Diabolical5777** [chamburr/modmail#96]
For the "viewsnippet" command, it would be nice and much easier in my opinion if it stated the number of existing snippets, preferably in square brackets since I think it looks the best, next to the embed title of "Snippets"
An example would be:

Snippets [3]
[the first snippet name]
[the first snippet content]

And so on

Code:
```py
all_pages = []
        for chunk in [res[i : i + 10] for i in range(0, len(res), 10)]:
            page = Embed(title=f"Snippets [{len(res)}]")
```

**Comment by chamburr** [comment]
I don't think the count would be useful
