### ISSUE TITLE
Send message only with command

### ISSUE THREAD

**Issue by dlsnyder8** [chamburr/modmail#99]
**Please describe the feature you'd like**
Currently, sending a message without the Modmail prefix in a channel will automatically send a message to the user, which could result in messages being sent accidentally to the user that may not be well received. Add a command which will require messages to be sent to a user using the `=reply` or `=areply` commands, and all other messages will be ignored.

**Describe the motivation for the feature**
It's a feature that's been requested multiple times throughout the years, but has never been implemented. Adding it as an optional feature for servers to enable or disable would help to prevent messages being accidentally sent through the system that the staff of a server may not want.

**Comment by SnowyJaguar1034** [comment]
[This refers to suggestion 163](https://canary.discord.com/channels/576016832956334080/576765354051633178/738611528466432050)
